In [1]:
import pandas as pd
data=pd.read_csv("./diabetes.csv")
data=pd.DataFrame(data)
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV, train_test_split
import numpy as np

In [3]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [2]:
x = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
        'BMI', 'DiabetesPedigreeFunction', 'Age']
y = ['Outcome']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(data[x], data[y], test_size=0.2, random_state=121)

In [5]:
data[x]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [6]:
dtree = DecisionTreeClassifier()

parameters = {'max_depth': [5,6,7], 'min_samples_split':[2,3]}


grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(X_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score','rank_test_score', 'split0_test_score', 'split1_test_score','split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 5, 'min_samples_split': 2}",0.719815,2,0.746341,0.726829,0.686275
1,"{'max_depth': 5, 'min_samples_split': 3}",0.724725,1,0.741463,0.726829,0.705882
2,"{'max_depth': 6, 'min_samples_split': 2}",0.701897,4,0.736585,0.702439,0.666667
3,"{'max_depth': 6, 'min_samples_split': 3}",0.697019,6,0.726829,0.697561,0.666667
4,"{'max_depth': 7, 'min_samples_split': 2}",0.701905,3,0.726829,0.707317,0.671569
5,"{'max_depth': 7, 'min_samples_split': 3}",0.698637,5,0.721951,0.712195,0.661765

In [7]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

GridSearchCV 최적 파라미터: {'max_depth': 5, 'min_samples_split': 3}
GridSearchCV 최고 정확도:0.7247
테스트 데이터 세트 정확도: 0.7662